import type {Metadata} from 'next'
import {Noto_Sans} from 'next/font/google'

import './globals.css'

import React from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const sansFont = Noto_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang='en'
      className='min-h-screen'>
      <body className={`antialiased min-h-screen ${sansFont.className}`}>{children}</body>
    </html>
  )
}
